services:
  postgres:
    image: postgres:15 # Replace with the desired version of PostgreSQL
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres # Replace with your desired username
      POSTGRES_PASSWORD: 123 # Replace with your desired password
      POSTGRES_DB: grocery_store # Replace with your desired database name
    ports:
      - "5432:5432" # Maps the container's port 5432 to your host's port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persists the database data

volumes:
  postgres_data:
    driver: local